# Generated by Django 6.0.1 on 2026-04-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
                ('first_club', models.CharField(max_length=120)),
                ('current_club', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
